# Generated by Django 2.0.2 on 2018-03-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('birth', models.CharField(max_length=15)),
                ('pesel', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=30)),
                ('phone_no', models.IntegerField()),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=6)),
                ('date', models.DateField()),
                ('secret', models.CharField(max_length=10)),
            ],
        ),
    ]
